- packages/components/src/Shared/ColorPicker/index.tsx
- packages/components/src/Shared/ColorTempPicker/index.tsx
- packages/components/src/Shared/Ripples/index.tsx
- packages/core/src/HassConnect/Provider.tsx
- packages/core/src/HassConnect/token-storage.ts
- packages/core/src/hooks/useHash/index.tsx
- https://github.com/shannonhochkins/ha-component-kit/issues/16
- Fallback cases for window properties have been added
> Handling cases where window properties aren't provided

- packages/components/package.json
- packages/components/src/Shared/ClimateControls/index.tsx
- packages/core/package.json
- stories/2.testConnection.stories.tsx
Enforcing npm/node versions in the engines property of the packages
> enforcing npm version in packages

- CHANGELOG.md
- packages/components/package.json
- packages/components/src/Cards/ButtonCard/ButtonCard.test.tsx
- packages/components/src/Cards/ButtonCard/index.tsx
- packages/components/src/Cards/FabCard/FabCard.stories.tsx
- packages/components/src/Cards/FabCard/index.tsx
- packages/components/src/Cards/RoomCard/index.tsx
- packages/components/src/Cards/TriggerCard/TriggerCard.stories.tsx
- packages/components/src/Cards/TriggerCard/index.tsx
- fixed onclick bug for FabCard and ButtonCard
> Fab Card Fixes

- hass-connect-fake/mocks/fake-call-service/mediaPlayer.ts
- packages/core/package.json
Storybook fix - seek api not implemented in fake api
> Media Player

- DEPLOY.md
- ROADMAP.md
- hass-connect-fake/mocks/mockEntities.ts
- packages/core/.d.ts
- packages/core/src/hooks/index.ts
- packages/core/src/hooks/useLowDevices/index.ts
- packages/core/src/hooks/useLowDevices/useLowDevices.stories.tsx
- packages/core/tsconfig.json
- stories/3.roadmap.mdx
A new hook to retrieve entities that have a battery percentage lower than 20 (by default), you can also provide a different min/max threshold, blacklist and a whitelist.
> Adding useLowDevices hook

- DEPLOY.md
- packages/components/src/Cards/ButtonCard/index.tsx
- packages/components/src/Cards/ClimateCard/index.tsx
- packages/components/src/Cards/FabCard/index.tsx
- packages/components/src/Cards/RoomCard/RoomCard.stories.tsx
useLongPress was causing click events to fail on mobile devices for fab/button cards
> useLongPress - bugfix

- .storybook/preview.tsx
- README.md
- hass-connect-fake/mocks/mockEntities.ts
- packages/components/src/Cards/ButtonCard/index.tsx
- packages/components/src/Cards/ClimateCard/index.tsx
- packages/components/src/Cards/EntitiesCard/index.tsx
- packages/components/src/Cards/FabCard/index.tsx
- packages/components/src/Cards/GarbageCollectionCard/index.tsx
- packages/components/src/Cards/MediaPlayerCard/index.tsx
- packages/components/src/Cards/PictureCard/index.tsx
- packages/components/src/Cards/RoomCard/index.tsx
- packages/components/src/Cards/SidebarCard/index.tsx
- packages/components/src/Cards/TimeCard/index.tsx
- packages/components/src/Cards/TriggerCard/index.tsx
- packages/components/src/Cards/WeatherCard/index.tsx
- packages/components/src/Group/index.tsx
- packages/components/src/Shared/Column/index.tsx
- packages/components/src/Shared/Modal/index.tsx
- packages/components/src/Shared/RangeSlider/index.tsx
- packages/components/src/Shared/Ripples/index.tsx
- packages/components/src/Shared/Row/index.tsx
- packages/components/src/Shared/Tooltip/index.tsx
- packages/components/src/ThemeProvider/index.tsx
- packages/components/src/hooks/constants.ts
- packages/components/src/hooks/mq.ts
- packages/components/src/hooks/useDevice.ts
- packages/components/src/index.ts
- stories/0.overview.stories.tsx
- massive changes to responsive design - previously mobile/tablet layout was horrible, things were cut off and unreadable
> Responsive fixes

- packages/components/src/Shared/Modal/index.tsx
- packages/components/src/Shared/Tooltip/index.tsx
Small upgrades including classname added to elements within Modal, this is something I'll be adding to all components so it's easier to re-style things consumer side
> gitflow-feature-stash: modal-style-upgrades

- CHANGELOG.md
- packages/components/src/Cards/ButtonCard/ButtonCard.stories.tsx
- packages/components/src/Cards/ButtonCard/index.tsx
- packages/components/src/Cards/ClimateCard/index.tsx
- packages/components/src/Cards/FabCard/index.tsx
- packages/components/src/Cards/MediaPlayerCard/index.tsx
- packages/components/src/Cards/SensorCard/index.tsx
- packages/components/src/Cards/TimeCard/index.tsx
- packages/components/src/Cards/TriggerCard/index.tsx
- packages/components/src/Cards/WeatherCard/index.tsx
- packages/components/src/Shared/Modal/ModalByEntityDomain.tsx
- packages/components/src/Shared/Modal/index.tsx
- packages/components/src/index.ts
- packages/core/src/hooks/useHistory/index.ts
- packages/core/src/types/supported-services.ts
- packages/core/sync-local-types.cjs
- Small style fixes for the new button card layouts
- updating some documentation
- Updating types after latest home assistant release
> small-style-changes

- package-lock.json
- package.json
- packages/core/package.json
- packages/create-hakit/package.json
- packages/create-hakit/src/index.ts
- packages/create-hakit/template/.prettierignore
- packages/create-hakit/template/.prettierrc
- packages/create-hakit/template/scripts/deploy.ts
- packages/create-hakit/template/src/App.tsx
> fix: create-hakit missing deploy script + App.tsx ThemeProvider being outside HassConnect provider

- packages/core/src/hooks/useEntity/index.ts
- packages/core/src/types/supported-services.ts
Reported under issue #117 and has been rectified.
Tested the following cases:
1. When home assistant entity has a custom icon assigned, it will always use this and dynamic icons will not be used
2. When no icon is assigned in home assistant, it will choose an icon based on the state of the entity.
> gitflow-hotfix-stash: issue-117-icon-not-updating

- packages/components/src/Cards/WeatherCard/index.tsx
* Allow hiding weather card forecast toggle and day names
* Allow hiding title
* Add option to display multiple forecast rows
> Weather card enhancements

- packages/components/src/Shared/Entity/Alarm/AlarmControls/index.tsx
- packages/components/src/Shared/Entity/Miscellaneous/ButtonGroup/ButtonGroupButton/index.tsx
- packages/components/src/Shared/Modal/ModalByEntityDomain/AlarmControlPanel/index.tsx
- packages/components/src/Shared/Modal/ModalByEntityDomain/index.tsx
- packages/components/src/index.ts
Unsure the best way to add a story... Is there a list of dummy entities somewhere I can reference?
> Add alarm control panel buttons

- CHANGELOG.md
- packages/components/src/Shared/Alert/index.tsx
- packages/components/src/Shared/Modal/ModalByEntityDomain/AlarmControlPanel/index.tsx
- packages/components/src/Shared/Modal/ModalByEntityDomain/Camera/index.tsx
- packages/components/src/Shared/Modal/ModalByEntityDomain/Climate/index.tsx
- packages/components/src/Shared/Modal/ModalByEntityDomain/Cover/index.tsx
- packages/components/src/Shared/Modal/ModalByEntityDomain/Light/index.tsx
- packages/components/src/Shared/Modal/ModalByEntityDomain/MediaPlayer/index.tsx
- packages/components/src/Shared/Modal/ModalByEntityDomain/Person/index.tsx
- packages/components/src/Shared/Modal/ModalByEntityDomain/Switch/index.tsx
- packages/components/src/Shared/Modal/ModalByEntityDomain/Vacuum/index.tsx
- packages/components/src/Shared/Modal/ModalByEntityDomain/Weather/index.tsx
- packages/components/src/Shared/Modal/ModalByEntityDomain/index.tsx
- packages/components/src/ThemeProvider/ThemeControls.tsx
- packages/components/src/ThemeProvider/index.tsx
- packages/components/src/ThemeProvider/theme.ts
- packages/core/src/utils/index.ts
- packages/core/src/utils/time/time-ago.ts
> theme provider and modal changes

- packages/components/src/Cards/CameraCard/players/webrtc.tsx
Largely copied from the hass lovelace card, linked to in the source file.  Confirmed to work in my setup.
> Update webrtc streams to use native hass APIs

- packages/components/src/Cards/WeatherCard/index.tsx
> Evenly distribute weather forecast across rows; Round 'Feels Like' temp

- packages/components/src/Shared/Modal/index.tsx
Useful for wall-tablet-based dashboards, where users might walk away with a modal still open
> Add option to auto-close modals after N seconds

- packages/components/src/Cards/TimeCard/formatter.ts
- packages/components/src/Cards/TimeCard/index.tsx
- packages/components/src/Cards/TimeCard/types.ts
Easier than forcing users to write their own formatter just to append a suffix
> Add suffix to date format string options

- package-lock.json
- packages/components/README.md
- packages/core/README.md
- packages/create-hakit/package.json
- packages/create-hakit/src/index.ts
- packages/create-hakit/src/socket.ts
- stories/2.gettingStarted.mdx
Improvements to the create-hakit command
> Adding more features to terminal wizard

- packages/core/scripts/sync-user-types/index.ts
- packages/create-hakit/src/index.ts
- packages/create-hakit/template/.env
- packages/create-hakit/template/.env.development
- packages/create-hakit/template/README.md
- packages/create-hakit/template/scripts/deploy.ts
- packages/create-hakit/template/scripts/sync-types.ts
- stories/3.deployment.mdx
Fixes [issue](https://github.com/shannonhochkins/ha-component-kit/issues/218)
> Fixing some security concerns

- packages/create-hakit/src/index.ts
Fixes [issue](https://github.com/shannonhochkins/ha-component-kit/issues/230)
Prompts package was missing in create package.
> Adding missing dependancy
